openapi: 3.0.0
paths:
  /admins/admins:
    get:
      tags:
        - admins
      summary: /admins/admins
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/users:
    get:
      tags:
        - admins
      summary: /admins/users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/events:
    get:
      tags:
        - admins
      summary: /admins/events
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/violations:
    get:
      tags:
        - admins
      summary: /admins/violations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/comments:
    get:
      tags:
        - admins
      summary: /admins/comments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
