openapi: 3.0.0
paths:
  /admins/admins:
    get:
      tags:
        - admins
      summary: alle Admins abfragen
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/users:
    get:
      tags:
        - admins
      summary: alle Users abfragen
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/events:
    get:
      tags:
        - admins
      summary: alle Events abfragen
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/violations:
    get:
      tags:
        - admins
      summary: alle Violations abfragen
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/comments:
    get:
      tags:
        - admins
      summary: alle Comments abfragen
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admins/users/5:
    delete:
      tags:
        - admins
      summary: Löschen eins User anhand der UserId
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}