name: Run API Jest Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}                    # Benutzername für MySQL
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}            # Passwort für den MySQL-Benutzer
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}            # Name der Datenbank
        ports:
          - 3306:3306
        options: >-
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.1

      - name: Install API dependencies
        run: npm install
        working-directory: ./  # Passe diesen Pfad an, falls notwendig

      - name: Create .env.test.local
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env.test.local
          echo "DB_HOST=localhost" >> .env.test.local
          echo "DB_USERNAME=${{ secrets.MYSQL_USER }}" >> .env.test.local
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env.test.local
          echo "DB_NAME=${{ secrets.MYSQL_DATABASE }}" >> .env.test.local
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test.local
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> .env.test.local

      - name: Wait for MySQL
        run: |
          export MYSQL_PWD="${{ secrets.MYSQL_PASSWORD }}"
          while ! mysqladmin ping -h"localhost" -u"${{ secrets.MYSQL_USER }}" --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Setup Database with SQL script
        run: |
          echo "Setting up the database structure..."
          mysql -h localhost -u${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} < db_script/test_veranstaltungskalender_ford_fiesta.sql

      - name: Run Jest tests
        run: npm run test
        working-directory: ./  # Passe diesen Pfad an, falls notwendig
